In [1]:
import pandas as pd

df = pd.read_csv("../data/Womens Clothing E-Commerce Reviews.csv")

print(df.shape)
df.head()

(23486, 11)

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

In [3]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [4]:
df.describe(include="all")

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
count,23486.000000,23486.000000,23486.000000,19676,22641,23486.000000,23486.000000,23486.000000,23472,23472,23472
unique,NaN,NaN,NaN,13993,22634,NaN,NaN,NaN,3,6,20
top,NaN,NaN,NaN,Love it!,Perfect fit and i've gotten so many compliment...,NaN,NaN,NaN,General,Tops,Dresses
freq,NaN,NaN,NaN,136,3,NaN,NaN,NaN,13850,10468,6319
mean,11742.500000,918.118709,43.198544,NaN,NaN,4.196032,0.822362,2.535936,NaN,NaN,NaN
std,6779.968547,203.298980,12.279544,NaN,NaN,1.110031,0.382216,5.702202,NaN,NaN,NaN
min,0.000000,0.000000,18.000000,NaN,NaN,1.000000,0.000000,0.000000,NaN,NaN,NaN
25%,5871.250000,861.000000,34.000000,NaN,NaN,4.000000,1.000000,0.000000,NaN,NaN,NaN
50%,11742.500000,936.000000,41.000000,NaN,NaN,5.000000,1.000000,1.000000,NaN,NaN,NaN
75%,17613.750000,1078.000000,52.000000,NaN,NaN,5.000000,1.000000,3.000000,NaN,NaN,NaN
max,23485.000000,1205.000000,99.000000,NaN,NaN,5.000000,1.000000,122.000000,NaN,NaN,NaN

In [5]:
df.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [7]:
df[
    df["Division Name"].isna() |
    df["Department Name"].isna() |
    df["Class Name"].isna()
][
    [
        "Clothing ID",
        "Age",
        "Title",
        "Review Text",
        "Rating",
        "Recommended IND",
        "Division Name",
        "Department Name",
        "Class Name"
    ]
]

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Division Name,Department Name,Class Name
9444,72,25,My favorite socks!!!,"I never write reviews, but these socks are so ...",5,1,NaN,NaN,NaN
13767,492,23,So soft!,I just love this hoodie! it is so soft and com...,5,1,NaN,NaN,NaN
13768,492,49,Wardrobe staple,Love this hoodie. so soft and goes with everyt...,5,1,NaN,NaN,NaN
13787,492,48,NaN,NaN,5,1,NaN,NaN,NaN
16216,152,36,Warm and cozy,"Just what i was looking for. soft, cozy and warm.",5,1,NaN,NaN,NaN
16221,152,37,Love!,I am loving these. they are quite long but are...,5,1,NaN,NaN,NaN
16223,152,39,"""long and warm""",These leg warmers are perfect for me. they are...,5,1,NaN,NaN,NaN
18626,184,34,Nubby footless tights,"These are amazing quality. i agree, size up to...",5,1,NaN,NaN,NaN
18671,184,54,New workhorse,These tights are amazing! if i care for them w...,5,1,NaN,NaN,NaN
20088,772,50,Comfy sweatshirt!,This sweatshirt is really nice! it's oversize...,5,1,NaN,NaN,NaN
21532,665,43,So worth it!,Got these on sale...absolutely love eberjey! f...,5,1,NaN,NaN,NaN
22997,136,47,"Charcoal, pale gray, a bit of silver!","These socks are soft and comfortable, and they...",5,1,NaN,NaN,NaN
23006,136,33,Cute itsy socks,"Love polkadots, love sparkle. these little soc...",5,1,NaN,NaN,NaN
23011,136,36,Super socks,I love these little socks ? and the dots spark...,5,1,NaN,NaN,NaN

In [8]:
# Count missing values before cleaning
missing_review_text = df["Review Text"].isna().sum()

missing_division = df["Division Name"].isna().sum()
missing_department = df["Department Name"].isna().sum()
missing_class = df["Class Name"].isna().sum()

print("Missing Review Text:", missing_review_text)
print("Missing Division:", missing_division)
print("Missing Department:", missing_department)
print("Missing Class:", missing_class)

Missing Review Text: 845
Missing Division: 14
Missing Department: 14
Missing Class: 14

In [10]:
# Handle missing review text
df["Review Text"] = df["Review Text"].fillna("")

# Handle missing categories
for col in ["Division Name", "Department Name", "Class Name"]:
    df[col] = df[col].fillna("Unknown")

In [11]:
products = df[
    [
        "Clothing ID",
        "Division Name",
        "Department Name",
        "Class Name"
    ]
].drop_duplicates()

print(products.shape)
products.head()

(1402, 4)

   Clothing ID   Division Name Department Name Class Name
0          767       Initmates        Intimate  Intimates
1         1080         General         Dresses    Dresses
2         1077         General         Dresses    Dresses
3         1049  General Petite         Bottoms      Pants
4          847         General            Tops    Blouses

In [12]:
reviews = df[
    [
        "Unnamed: 0",
        "Clothing ID",
        "Age",
        "Title",
        "Review Text",
        "Rating",
        "Recommended IND",
        "Positive Feedback Count"
    ]
].copy()

reviews = reviews.rename(columns={
    "Unnamed: 0": "Review ID"
})

print(reviews.shape)
reviews.head()

(23486, 8)

,Review ID,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6

In [13]:
conflicts = (
    products.groupby("Clothing ID")
    .agg({
        "Department Name": "nunique",
        "Class Name": "nunique"
    })
)

conflicts = conflicts[
    (conflicts["Department Name"] > 1) |
    (conflicts["Class Name"] > 1)
]

print(conflicts)
print("Number of conflicting Clothing IDs:", len(conflicts))

             Department Name  Class Name
Clothing ID
1119                       1           2
Number of conflicting Clothing IDs: 1

In [14]:
invalid_ratings = reviews[
    ~reviews["Rating"].isin([1, 2, 3, 4, 5])
]

print(invalid_ratings)
print("Invalid ratings:", len(invalid_ratings))

Empty DataFrame
Columns: [Review ID, Clothing ID, Age, Title, Review Text, Rating, Recommended IND, Positive Feedback Count]
Index: []
Invalid ratings: 0

In [15]:
invalid_recommendations = reviews[
    ~reviews["Recommended IND"].isin([0, 1])
]

print(invalid_recommendations)
print("Invalid recommendation values:", len(invalid_recommendations))

Empty DataFrame
Columns: [Review ID, Clothing ID, Age, Title, Review Text, Rating, Recommended IND, Positive Feedback Count]
Index: []
Invalid recommendation values: 0

In [16]:
products.to_csv("../outputs/products.csv", index=False)
reviews.to_csv("../outputs/cleaned_reviews.csv", index=False)

print("Products saved:", products.shape)
print("Reviews saved:", reviews.shape)

Products saved: (1402, 4)
Reviews saved: (23486, 8)

In [17]:
products.to_csv("../outputs/products.csv", index=False)
reviews.to_csv("../outputs/cleaned_reviews.csv", index=False)

print("Products saved:", products.shape)
print("Reviews saved:", reviews.shape)

Products saved: (1402, 4)
Reviews saved: (23486, 8)